angular.module '%module%.common'
.constant 'SERIOUS_GAME_URL', '%SERIOUS_GAME_URL%'
.constant 'COMPETITION_URL', '%COMPETITION_URL%'
.constant 'AUTHENTICATOR_URL', '%AUTHENTICATOR_URL%'
.constant 'FLUX_URL', '%FLUX_URL%'
